# Generated by Django 3.1.7 on 2021-03-14 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='file',
            options={'verbose_name': '文件', 'verbose_name_plural': '文件'},
        ),
        migrations.AlterField(
            model_name='file',
            name='upload',
            field=models.FileField(upload_to='files/', verbose_name='上传文件'),
        ),
    ]
