# Generated by Django 3.1.7 on 2021-03-16 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0003_auto_20210314_1924'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='name',
            field=models.CharField(max_length=255, null=True, verbose_name='文件名'),
        ),
    ]
