# Generated by Django 3.1.7 on 2021-03-14 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detail', '0005_post_is_top'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='标题')),
                ('content', models.TextField(verbose_name='更新内容')),
            ],
            options={
                'verbose_name': '更新日志',
                'verbose_name_plural': '更新日志',
            },
        ),
    ]
