# Generated by Django 3.1.7 on 2021-03-14 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detail', '0006_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='title',
            field=models.DateField(auto_now_add=True, verbose_name='标题'),
        ),
    ]
