# Generated by Django 3.1.7 on 2021-03-14 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detail', '0007_auto_20210314_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='title',
            field=models.CharField(max_length=255, verbose_name='标题'),
        ),
    ]
