# Generated by Django 3.1.7 on 2021-03-14 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detail', '0009_auto_20210314_1211'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='log',
            options={'ordering': ['-title'], 'verbose_name': '更新日志', 'verbose_name_plural': '更新日志'},
        ),
    ]
